version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nabeey_postgres
    restart: always
    environment:
      POSTGRES_DB: NabeeyDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nabeey_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d NabeeyDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapi:
    image: nabeey_webapi
    container_name: nabeey_webapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:DefaultConnection=Host=postgres;Database=NabeeyDb;Port=5432;User Id=postgres;Password=postgres;
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - nabeey_network

volumes:
  postgres_data:

networks:
  nabeey_network:
    driver: bridge
